cleanup

diff --git a/promote b/promote
--- a/promote
+++ b/promote
@@ -1,9 +1,67 @@
-# promote 
-# empty push commit push with /promote
-# empty push commit PR with /promote
+#!/bin/bash -e
+set -o pipefail
 
-ENV=${1:-dev}
-METHOD=${2:-pr}   
+ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"/..
+
+# Print help message
+function print_help() {
+  echo "Usage: $0 [--from] [--to] [--repo] [-h|--help]" 
+  echo "  --env       Default 'dev', env to promote from - dev promotes to stage, stage to prod" 
+  echo "  --repo      Default git repo in current directory"
+  echo "  --method    push direct or pull_request"
+  echo
+  echo "Example usage: \`$0 --env dev --method=push  # promotes from dev to stage, using push"
+  echo "Example usage: \`$0 --env dev --method=pr  # promotes from dev to stage, using pr" 
+  echo "Example usage: \`$0 --env stage --method=pr # promotes from stage to prod, using pr" 
+} 
+
+ENV=dev
+METHOD=push   
+while [[ $# -gt 0 ]]; do
+  key=$1
+  case $key in
+    --env)
+      shift 
+      ENV=$1
+      shift 
+      ;; 
+    --method)
+      shift
+      METHOD=$1
+      shift 
+      ;;
+    --repo)
+      shift
+      GITOPS_REPO=$1 
+      shift 
+      ;;
+    --push) 
+      METHOD=push 
+      shift 
+      ;;
+    --pr) 
+      METHOD=pr 
+      shift 
+      ;;
+    --current) 
+        echo "Using current"
+        if [ -d .git ]; then
+            GITOPS_REPO=$(git config --get remote.origin.url)
+        else 
+            echo "--current specified but not a git repo"
+        fi 
+        shift
+      ;; 
+    -h|--help)
+      print_help
+      exit 0
+      ;;
+    *)
+      shift
+      ;;
+  esac
+done
+ 
  
 if [ $ENV == "dev" ]; then 
     ENV_DEST=stage
@@ -14,6 +72,20 @@ fi
 if [ -z $ENV_DEST ]; then 
     echo "promotion env should be dev (promotes to stage) or stage (promotes to prod)"
 fi  
+if [ -z $GITOPS_REPO ]; then 
+    echo "Missing Gitops Repo to promote"
+    echo "use --repo for any repo and --current for repo in the current directory"
+    exit 
+fi  
+ 
+echo "Repo: $GITOPS_REPO"
+echo "Promote from $ENV to $ENV_DEST via $METHOD" 
+
+DIR=$(mktemp -d)
+cd $DIR
+pwd
+git clone $GITOPS_REPO promote-repo 
+cd promote-repo 
 if [ "$METHOD" == "pr" ]; then  
     echo 
     echo "Promote from $ENV to $ENV_DEST via Pull-Request"
